#!/usr/bin/env bash
# Generates infra/ansible/inventory/hosts.yml from live Terraform outputs.
# Run from the repo root after `terraform apply` in infra/terraform/.
#
# Requires: terraform (initialised backend), jq, aws CLI with active
# credentials, and access to the S3 bucket used by amazon.aws.aws_ssm.
set -euo pipefail

TF_DIR="infra/terraform"
OUT="infra/ansible/inventory/hosts.yml"

for cmd in terraform jq aws; do
  command -v "${cmd}" >/dev/null 2>&1 || { echo "error: ${cmd} not found in PATH" >&2; exit 1; }
done

OUTPUTS=$(cd "$TF_DIR" && terraform output -json)

PROJECT=$(echo "$OUTPUTS" | jq -r '.project_name.value')
REGION=$(echo  "$OUTPUTS" | jq -r '.region.value')

app_id=$(echo       "$OUTPUTS" | jq -r '.instance_ids.value.app')
worker_id=$(echo    "$OUTPUTS" | jq -r '.instance_ids.value.worker')
db_id=$(echo        "$OUTPUTS" | jq -r '.instance_ids.value.db')
prom_id=$(echo      "$OUTPUTS" | jq -r '.instance_ids.value.prometheus')
grafana_id=$(echo   "$OUTPUTS" | jq -r '.instance_ids.value.grafana')

app_ip=$(echo       "$OUTPUTS" | jq -r '.instance_private_ips.value.app')
worker_ip=$(echo    "$OUTPUTS" | jq -r '.instance_private_ips.value.worker')
db_ip=$(echo        "$OUTPUTS" | jq -r '.instance_private_ips.value.db')
prom_ip=$(echo      "$OUTPUTS" | jq -r '.instance_private_ips.value.prometheus')
grafana_ip=$(echo   "$OUTPUTS" | jq -r '.instance_private_ips.value.grafana')

# ECR registry URI — derived from the caller's account so CI (OIDC) and
# local runs both resolve to the correct account without hard-coding.
ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
ECR_REGISTRY="${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com"
DEFAULT_SSM_BUCKET="$(printf '%s' "${PROJECT}-ssm-${ACCOUNT_ID}" | tr '[:upper:]' '[:lower:]')"
SSM_BUCKET="${ANSIBLE_SSM_BUCKET:-${DEFAULT_SSM_BUCKET}}"

if ! aws s3api head-bucket --bucket "${SSM_BUCKET}" >/dev/null 2>&1; then
  cat >&2 <<EOF
error: Ansible SSM transfer bucket missing or inaccessible: ${SSM_BUCKET}

The amazon.aws.aws_ssm connection plugin stages Ansible modules through S3.
Create the bucket once for this AWS account, or override the expected name
with ANSIBLE_SSM_BUCKET before rerunning this script.

See docs/deploy.md for the supported setup.
EOF
  exit 1
fi

# Image tag to deploy. server.yml pushes one traceable tag per merge to main
# (DATE-SHORTSHA-MSG format; no mutable :main or :latest alias).
# When DEPLOY_IMAGE_TAG is not set, query ECR for the most recently pushed tag.
# Override locally: export DEPLOY_IMAGE_TAG=20260420-a3f9c2b-add-jwt-auth
IMAGE_TAG="${DEPLOY_IMAGE_TAG:-}"
if [[ -z "${IMAGE_TAG}" ]]; then
  IMAGE_TAG=$(aws ecr describe-images \
    --repository-name "${PROJECT}" \
    --region "${REGION}" \
    --query 'sort_by(imageDetails,&imagePushedAt)[-1].imageTags[0]' \
    --output text 2>/dev/null || true)
  if [[ -z "${IMAGE_TAG}" || "${IMAGE_TAG}" == "None" ]]; then
    echo "error: no images found in ECR repository ${PROJECT}. Push an image first." >&2
    exit 1
  fi
fi
CONTAINER_IMAGE="${ECR_REGISTRY}/${PROJECT}:${IMAGE_TAG}"

mkdir -p "$(dirname "$OUT")"

cat > "$OUT" <<EOF
# Generated by scripts/render-inventory.sh — do not edit by hand.
# Source of truth: infra/terraform outputs. Re-run after terraform apply.

all:
  vars:
    ansible_connection: amazon.aws.aws_ssm
    ansible_aws_ssm_region: ${REGION}
    ansible_aws_ssm_bucket_name: ${SSM_BUCKET}
    ansible_user: ssm-user
    ansible_python_interpreter: /usr/bin/python3
    aws_region: ${REGION}
    ecr_registry: ${ECR_REGISTRY}
    onboarding_platform_ecr_repository: ${PROJECT}
    onboarding_platform_container_image: ${CONTAINER_IMAGE}
  children:
    app:
      hosts:
        ${PROJECT}-app:
          ansible_host: ${app_id}
          private_ip: ${app_ip}
    worker:
      hosts:
        ${PROJECT}-worker:
          ansible_host: ${worker_id}
          private_ip: ${worker_ip}
    db:
      hosts:
        ${PROJECT}-db:
          ansible_host: ${db_id}
          private_ip: ${db_ip}
    prometheus:
      hosts:
        ${PROJECT}-prometheus:
          ansible_host: ${prom_id}
          private_ip: ${prom_ip}
    grafana:
      hosts:
        ${PROJECT}-grafana:
          ansible_host: ${grafana_id}
          private_ip: ${grafana_ip}
EOF

echo "Inventory written to $OUT (image: ${CONTAINER_IMAGE}, ssm bucket: ${SSM_BUCKET})"
