#!/usr/bin/env bash
# Generates infra/ansible/inventory/hosts.yml from live Terraform outputs.
# Run from the repo root after `terraform apply` in infra/terraform/.
#
# Requires: terraform (initialised backend), jq, aws CLI with active credentials.
set -euo pipefail

TF_DIR="infra/terraform"
OUT="infra/ansible/inventory/hosts.yml"

for cmd in terraform jq aws; do
  command -v "${cmd}" >/dev/null 2>&1 || { echo "error: ${cmd} not found in PATH" >&2; exit 1; }
done

OUTPUTS=$(cd "$TF_DIR" && terraform output -json)

PROJECT=$(echo "$OUTPUTS" | jq -r '.project_name.value')
REGION=$(echo  "$OUTPUTS" | jq -r '.region.value')

app_id=$(echo       "$OUTPUTS" | jq -r '.instance_ids.value.app')
worker_id=$(echo    "$OUTPUTS" | jq -r '.instance_ids.value.worker')
db_id=$(echo        "$OUTPUTS" | jq -r '.instance_ids.value.db')
prom_id=$(echo      "$OUTPUTS" | jq -r '.instance_ids.value.prometheus')
grafana_id=$(echo   "$OUTPUTS" | jq -r '.instance_ids.value.grafana')

app_ip=$(echo       "$OUTPUTS" | jq -r '.instance_private_ips.value.app')
worker_ip=$(echo    "$OUTPUTS" | jq -r '.instance_private_ips.value.worker')
db_ip=$(echo        "$OUTPUTS" | jq -r '.instance_private_ips.value.db')
prom_ip=$(echo      "$OUTPUTS" | jq -r '.instance_private_ips.value.prometheus')
grafana_ip=$(echo   "$OUTPUTS" | jq -r '.instance_private_ips.value.grafana')

# ECR registry URI — derived from the caller's account so CI (OIDC) and
# local runs both resolve to the correct account without hard-coding.
ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
ECR_REGISTRY="${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com"

# Image tag to deploy. server.yml pushes two tags on every merge to main:
#   - Versioned: DATE-SHORTSHA-MSG  (for identification and rollback)
#   - Stable:    main               (always points at the latest good build)
# infra.yml uses `main` so Ansible always pulls the current good image
# without needing to pass the versioned tag across workflow boundaries.
# Override locally: export DEPLOY_IMAGE_TAG=20260420-a3f9c2b-add-jwt-auth
IMAGE_TAG="${DEPLOY_IMAGE_TAG:-main}"
CONTAINER_IMAGE="${ECR_REGISTRY}/${PROJECT}:${IMAGE_TAG}"

mkdir -p "$(dirname "$OUT")"

cat > "$OUT" <<EOF
# Generated by scripts/render-inventory.sh — do not edit by hand.
# Source of truth: infra/terraform outputs. Re-run after terraform apply.

all:
  vars:
    ansible_connection: amazon.aws.aws_ssm
    ansible_aws_ssm_region: ${REGION}
    ansible_user: ec2-user
    ansible_python_interpreter: /usr/bin/python3
    aws_region: ${REGION}
    ecr_registry: ${ECR_REGISTRY}
    onboarding_platform_ecr_repository: ${PROJECT}
    onboarding_platform_container_image: ${CONTAINER_IMAGE}
  children:
    app:
      hosts:
        ${PROJECT}-app:
          ansible_host: ${app_id}
          private_ip: ${app_ip}
    worker:
      hosts:
        ${PROJECT}-worker:
          ansible_host: ${worker_id}
          private_ip: ${worker_ip}
    db:
      hosts:
        ${PROJECT}-db:
          ansible_host: ${db_id}
          private_ip: ${db_ip}
    prometheus:
      hosts:
        ${PROJECT}-prometheus:
          ansible_host: ${prom_id}
          private_ip: ${prom_ip}
    grafana:
      hosts:
        ${PROJECT}-grafana:
          ansible_host: ${grafana_id}
          private_ip: ${grafana_ip}
EOF

echo "Inventory written to $OUT (image: ${CONTAINER_IMAGE})"
