#!/usr/bin/env bash
# Generates infra/ansible/inventory/hosts.yml from live Terraform outputs.
# Run from the repo root after `terraform apply` in infra/terraform/.
#
# Requires: terraform (with initialised backend), jq
set -euo pipefail

TF_DIR="infra/terraform"
OUT="infra/ansible/inventory/hosts.yml"

OUTPUTS=$(cd "$TF_DIR" && terraform output -json)

PROJECT=$(echo "$OUTPUTS" | jq -r '.project_name.value')
REGION=$(echo  "$OUTPUTS" | jq -r '.region.value')

app_id=$(echo       "$OUTPUTS" | jq -r '.instance_ids.value.app')
worker_id=$(echo    "$OUTPUTS" | jq -r '.instance_ids.value.worker')
db_id=$(echo        "$OUTPUTS" | jq -r '.instance_ids.value.db')
prom_id=$(echo      "$OUTPUTS" | jq -r '.instance_ids.value.prometheus')
grafana_id=$(echo   "$OUTPUTS" | jq -r '.instance_ids.value.grafana')

app_ip=$(echo       "$OUTPUTS" | jq -r '.instance_private_ips.value.app')
worker_ip=$(echo    "$OUTPUTS" | jq -r '.instance_private_ips.value.worker')
db_ip=$(echo        "$OUTPUTS" | jq -r '.instance_private_ips.value.db')
prom_ip=$(echo      "$OUTPUTS" | jq -r '.instance_private_ips.value.prometheus')
grafana_ip=$(echo   "$OUTPUTS" | jq -r '.instance_private_ips.value.grafana')

cat > "$OUT" <<EOF
# Generated by scripts/render-inventory.sh — do not edit by hand.
# Source of truth: infra/terraform outputs. Re-run after terraform apply.

all:
  vars:
    ansible_connection: amazon.aws.aws_ssm
    ansible_aws_ssm_region: ${REGION}
    ansible_user: ec2-user
    ansible_python_interpreter: /usr/bin/python3
  children:
    app:
      hosts:
        ${PROJECT}-app:
          ansible_host: ${app_id}
          private_ip: ${app_ip}
    worker:
      hosts:
        ${PROJECT}-worker:
          ansible_host: ${worker_id}
          private_ip: ${worker_ip}
    db:
      hosts:
        ${PROJECT}-db:
          ansible_host: ${db_id}
          private_ip: ${db_ip}
    prometheus:
      hosts:
        ${PROJECT}-prometheus:
          ansible_host: ${prom_id}
          private_ip: ${prom_ip}
    grafana:
      hosts:
        ${PROJECT}-grafana:
          ansible_host: ${grafana_id}
          private_ip: ${grafana_ip}
EOF

echo "Inventory written to $OUT"
